### ISSUE TITLE
markdownify

### ISSUE THREAD

**Issue by git-no** [vwochnik/jekyll-language-plugin#17]
It seems to me command `t` and also `tinclude` do not format/print data as markdown, the text is printed always as raw data including markdown signs, e.g.

`{% t 'key_with_markdown_string_behind %}`

or 

`{% tinclude filename.md %}`

Printing markdown can be accomplished with Liquid in general like so: 
`{{ string_including_markdown | markdownify }}`

Does and how support  `t`or `tinclude` the output of markdown format?

Of course a workaround would be:
`{% capture data %} {% tinclude filename.md %} {% endcapture %}
{{ data | markdownify }}`
But this is more complicated and would need much more code and would break the easy handling of `t`.

Thank you very much.

**Comment by vwochnik** [comment]
Currently, using `capture` is the only way of doing this as far as I know. You can always `tinclude` something within a markdown file and it gets parsed but as soon as you are within a `liquid` template, you have to use `capture` and `markdownify`. But hey, that's the same the regular `include` works, right?

IMO, there is not a huge potential to implement this. I cannot imagine a use case for this that is relevant enough but Im always open for discussion.

**Comment by git-no** [comment]
Thank you for the quick response time.

For `t`I would agree to use capture. But I would assume for `tinclude` there is a bigger use case to print formated markdown. Also in your example (included in the repo) are a file about.md included by `tincluded' but not parsed as markdown. What sense does it make to include a markdown file but print this as raw and not formatted? I would assume by including a markdown file the user expects to view it as markdown (possible scenario: html file includes a markdown file). Otherwise he would include a txt file, which is also within the example of the repo. What do you think?

**Comment by vwochnik** [comment]
How do you know the markdown included from the `about.md` isn't rendered? When you include from `.html` files, that certainly is the case without `capture` and `markdownify` but `.md` files should work just fine.

`tinclude` extends the `jekyll` `include` directive and I will not make any adaptions to that feature of this plugin since it is kept as simple and streamlined as possible.
