### ISSUE TITLE
Question: Differences to existing jekyll-multiple-languages-plugin?

### ISSUE THREAD

**Issue by escapedcat** [vwochnik/jekyll-language-plugin#2]
I was just checking on how to do multilang pages with Jekyll and stumbled across different approaches and plugins.

Could you point out main differences to this plugin?:
https://github.com/screeninteraction/jekyll-multiple-languages-plugin
(The PR to support v3 will be merged soon)

Is it mainly this?

> Is does not require a complex setup process unlike some other internationalization plugins.

Sorry if this is not the right place to ask, but I thought it could be interesting for others as well.

**Comment by vwochnik** [comment]
No! [`jekyll-multiple-languages-plugin`](https://github.com/screeninteraction/jekyll-multiple-languages-plugin) is a very simplistic plugin composed of a few Liquid tags providing translation of strings and internationalized includes.

[`jekyll-language-plugin`](https://github.com/vwochnik/jekyll-language-plugin) is much more then just a `translation` and an internationalized `include` tag, although of course supported. The plugin provides support for language-specific pages and posts via the `language` or `languages` front-matter but also internationalized pages, templates and posts using the aforementioned `translation` and `include` Liquid tags.

Furthermore, the plugin supports localized date and time. It's also very flexible and easy to setup. Why don't you clone the repository and build the example site?

**Comment by escapedcat** [comment]
Thanks for the fast reply! Will do. I just wanted to ask before I start looking closer into it.

**Comment by vwochnik** [comment]
I reckon you'll like it if you're about to develop a multilingual site. If you have further questions, just open another issue. But I think the example site is very insightful.

**Comment by vwochnik** [comment]
Beware, I have just updated the example site plugin dependency from version `1.1.6` which was broken to version `1.1.7`. So if you have already checked out the repository, just make a `git pull`.
