### ISSUE TITLE
cannot work in github repository

### ISSUE THREAD

**Issue by johnliao52** [vwochnik/jekyll-language-plugin#20]
I clone the project and upload files in example directory as a github repository to my github account.
But got the following error:

The page build failed with the following error:

The tag `t` on line 4 in `_layouts/post.html` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

If you have any questions you can contact us by replying to this email.

**Comment by vwochnik** [comment]
This is expected. You have to build the project locally and then only commit the `_site` directory to the `gh-pages` branch. I have done this. See the [vincentwochnik.com](https://github.com/vwochnik/vincentwochnik.com) repository containing a [deploy script](https://github.com/vwochnik/vincentwochnik.com/blob/master/.deploy-script.sh) called by [`jekyll-deploy`](https://github.com/vwochnik/jekyll-deploy).

**Comment by johnliao52** [comment]
May I ask what is the reason why jekyll github cannot recognize tag 't'?

**Comment by vwochnik** [comment]
The build process utilized by GitHub Pages does not allow other plugins then those built into it. Thus, the plugin I develop including its `t` tag is not supported.
