### ISSUE TITLE
native language names

### ISSUE THREAD

**Issue by karstenBriksoft** [vwochnik/jekyll-language-plugin#23]
It appears the only way to print a language is using {% tl language %}
While it may seem reasonable to do that it actually requires the visitor of a webpage to understand the language he's on. A chinese visitor on an english page needs to know that "Chinese" refers to his language. It would really help if there was a tln (translate language native) tag that renders "de" as Deutsch and "en" as English. Wikipedia does it right already.

**Comment by vwochnik** [comment]
I have merged your pull request and released version 1.3.4.
