### ISSUE TITLE
Some strange problem

### ISSUE THREAD

**Issue by kropsi** [vwochnik/jekyll-language-plugin#29]
Strange experience. The following work for me:

```
<title>{% if page.title %}{{ page.title }}{% else %}{% t 'title' %} | {% endif %}
  {% t 'site.title' %}</title>
```

It uses `{% t 'title' %}` to set a title

The following doesn't work

```
<title>{% t 'title' %} | {% t 'site.title' %}</title>
```

It throws:

>  Liquid Exception: Key title not found in translation.

**Comment by vwochnik** [comment]
Do you have blog posts? If you leave the `if` statement away, then you must have defined a language `subset` for every page/post that you have. Otherwise the `title` key will not be found.

**Comment by vwochnik** [comment]
I have commented in the other issue you have opened.
