### ISSUE TITLE
Example: bundle install

### ISSUE THREAD

**Issue by escapedcat** [vwochnik/jekyll-language-plugin#3]
The example relies on 1.1.6. so I get:

```
bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'jekyll-language-plugin (= 1.1.6) ruby' in any of the gem sources listed in your Gemfile or available on this machine.
```

After changing it to 1.1.7 it works fine.

**Comment by vwochnik** [comment]
Thanks for the heads-up. Version `1.1.6` was yanked because it was broken. I have forgotten to update the `Gemfile` to version `1.1.7`. Fixed.

**Comment by escapedcat** [comment]
:+1:

**Comment by vwochnik** [comment]
@escapedcat how do you like the example? Would you suggest theming the site to make it more appealing or do you think that a bare-bone site is more illustrative on how to use the plugin?

**Comment by escapedcat** [comment]
Hey, good question.

I think barebone is totally fine. No need for styling.
I was just trying to add some **main** pages, not posts. So things like **about**, **contact**, **projects** for example.
If I want to _translate_ the URLs as well I find myself creating one file each with the same content, but different language option. Like:

**about.md**

```
---
layout: default
language: en
subset: about
---
{% tinclude about.md %}
```

and

**ueberuns.md**

```
---
layout: default
language: de
subset: about
---
{% tinclude about.md %}
```

Not sure if this is the way to go though. Or is the _permalink_-option still relevant?
To shorten things up... some different **main** pages would be great for the example page.
Also an `.md` example would be nice to show that not only `.txt`works in `_i18n`.

**Comment by vwochnik** [comment]
Ok, fair enough. I, however, would not rely on language-specific URLs. Just go with one `about.md` for English and German and then use a `tinclude` like you already do. Look into the [`default`](https://github.com/vwochnik/jekyll-language-plugin/blob/master/example/_layouts/default.html#L9-L13) layout where you can see the alternative language references inside the `head` tag. If you are using different files for each language, there are no references for alternative languages.

**Comment by escapedcat** [comment]
Oh, I see. Didn't see that. Thanks. Will check.

**Comment by escapedcat** [comment]
How to set a different page title in that case?

**Comment by vwochnik** [comment]
I have created an `about.md` page. See 0d15df675d7c2df1309bb6047d5399f534a3b116.

**Comment by vwochnik** [comment]
The page title is the `title` key in the page's `subset` of the language being rendered. Look into the bespoke `default` layout.

**Comment by escapedcat** [comment]
Awesome, thanks!
