### ISSUE TITLE
 Error:  different prefix: "/" 

### ISSUE THREAD

**Issue by bstarr322** [vwochnik/jekyll-language-plugin#30]
Hi there !

Thanks for this plugin.
At the moment, I am configuring multi language for our Jekyll based project, so I cloned this example repo and tried to launch on my windows local.

After bundle install, when I run `bundle exec jekyll serve`, it says the following errors.
`$ bundle exec jekyll serve
Configuration file: E:/projects/jekyll/jekyll-language-plugin/example/_config.yml
            Source: E:/projects/jekyll/jekyll-language-plugin/example
       Destination: E:/projects/jekyll/jekyll-language-plugin/example/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.2.0 | Error:  different prefix: "/" and "E:/projects/jekyll/jekyll-language-plugin/example"
`

I would be appreciated for any help !

Thanks.

**Comment by vwochnik** [comment]
Try the current version of Jekyll.
