### ISSUE TITLE
Links always point back to first language

### ISSUE THREAD

**Issue by jimmymcpeter** [vwochnik/jekyll-language-plugin#32]
I'm trying to use the link tag outlined here - https://jekyllrb.com/docs/templates/#link

```
<a href="{{ site.baseurl }}{% link support/index.md %}">{% t 'ui-text.navbar.support' %}</a>
```

The problem I'm finding is when viewing my `fr-ca` page, the hyperlink always points back to the first language I setup, `en-us`.  Both hyperlinks always equal `http://localhost:4000/en-us/support/`.  Do you have any recommendations on this?

**Comment by espen** [comment]
In my case it doesn't always point to the first language, it seems like it randomly uses a language. So some links are generated as 'en/page' while others are 'nb/side'. Or perhaps randomly is not the correct description as it seem to select the same language url constantly across pages/languages and server restart, so one link is always 'en' while another is always 'nb'.

**Comment by espen** [comment]
I ended up creating a plugin that solves this. So instead of using the standard 'link' I use 'link_lang'. https://gist.github.com/espen/641d14891999a22060af1079fd46bf9d

**Comment by vwochnik** [comment]
The `{% link %}` tag does not recognize the language plugin. You have to build the URL yourself.

```
<a href="{{ site.baseurl }}{{ page.language }}/path/to/post.html">{% t 'ui-text.navbar.support' %}</a>
```
