### ISSUE TITLE
error in the having footer translated

### ISSUE THREAD

**Issue by alexandre1985** [vwochnik/jekyll-language-plugin#33]
I am trying to use your plugin for my website language support.
I have read the wiki, looked and copy the examples code and still I can figure out where am I doing wrong with the beggining of my code.
When building I get this error:

>   Liquid Exception: No language specified for current page or post. in /_layouts/default.html
jekyll 3.6.2 | Error:  No language specified for current page or post.

I have published my code for better helping support. Please do a:
`git clone https://github.com/alexandre1985/teste.git`
to get my code that isn't working.

**Comment by faziloub** [comment]
i have same issue with home page tittle and description

**Comment by vwochnik** [comment]
I cannot clone your repository.

**Comment by alexandre1985** [comment]
It had some mistake on my part. Sorry and thank you
